version: "v1"
services:
  backend:
    image: saisrinivas300/ai-interview-agent-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: saisrinivas300/ai-interview-agent-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
